In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
%matplotlib inline

In [2]:
def random_imputation(df, feature):

    number_missing = df[feature].isnull().sum()
    observed_values = df.loc[df[feature].notnull(), feature]
    df.loc[df[feature].isnull(), feature] = np.random.choice(observed_values, number_missing, replace = True)
    
    return df

In [3]:
places =['andhra_pradesh','assam','bihar','chattissgarh','daman_diu_dadra_nagar_haveli','goa','himachal_pradesh','kerala','lakshadweep','madhya_pradesh','maharashtra','odisha','pondicherry','punjab','rajasthan','tripura','uttar_pradesh_uttarakhand','west_bengal']

In [4]:
df1 = pd.DataFrame()


for place in places:
    
    df = pd.read_csv("Ground_Water_Data/ground_water_quality_in_"+place+"-2014.csv",encoding = "unicode_escape")
    
    
    df1 = df1.append(df, ignore_index=True)
    if df1.empty:
        df1 = df
df.head()

,STATION CODE,LOCATIONS,STATE,TEMPERATURE ºC : Min,TEMPERATURE ºC : Max,TEMPERATURE ºC : Mean,pH : Min : 6.5-8.5,pH : Max : 6.5-8.5,pH : Mean : 6.5-8.5,CONDUCTIVITY (µmhos/cm) : Min,...,B.O.D. (mg/l) : Mean : < 3 mg/l,NITRATE- N+ NITRITE-N (mg/l) : Min,NITRATE- N+ NITRITE-N (mg/l) : Max,NITRATE- N+ NITRITE-N (mg/l) : Mean,FECAL COLIFORM (MPN/100ml) : Min : < 2500 MPN/100ml,FECAL COLIFORM (MPN/100ml) : Max : < 2500 MPN/100ml,FECAL COLIFORM (MPN/100ml) : Mean : < 2500 MPN/100ml,TOTAL COLIFORM (MPN/100ml) : Min : < 5000 MPN/100ml,TOTAL COLIFORM (MPN/100ml) : Max : < 5000 MPN/100ml,TOTAL COLIFORM (MPN/100ml) : Mean : < 5000 MPN/100ml
0,1767,"DURGAPUR TOWN,NEAR IISCO, BURDWAN, WEST BENGAL",WEST BENGAL,27.0,28.0,27.5,7.4,7.4,7.4,877,...,0.7,0.4,0.5,0.4,NaN,NaN,NaN,NaN,NaN,NaN
1,1768,"DURGAPUR TOWN, BURDWAN, WEST BENGAL",WEST BENGAL,31.0,33.0,32.0,6.9,7.4,7.2,656,...,0.9,0.3,0.5,0.4,NaN,NaN,NaN,NaN,NaN,NaN
2,1770,"NEAR IOC REFINERY HALDIA, WEST BENGAL",WEST BENGAL,35.0,35.0,35.0,7.1,7.3,7.2,2140,...,3.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1771,"KALYANI INDUSTRIAL AREA, NADIA, WEST BENGAL",WEST BENGAL,27.0,28.0,27.5,7.5,8.3,7.9,572,...,1.0,0.1,0.4,0.2,0.0,0.0,0.0,1.0,1.0,1.0
4,1772,"BARASAT MUNICIPALITY NORTH 24-P, WEST BENGAL",WEST BENGAL,28.0,28.0,28.0,7.1,8.0,7.5,696,...,0.8,0.1,0.5,0.3,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
missing_columns = df1.loc[:, df1.isnull().any()].columns.values
for feature in missing_columns:
    
    df1 = random_imputation(df1, feature)

for feature in missing_columns:
    df1 = random_imputation(df1,feature)
    

df1.to_csv('Ground_water_pre_processed/filled_groundwater.csv')